[project]
name = "robodk-pick-and-place"
version = "0.1.0"
description = "Pick and place task with RoboDK and Universal Robots"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "robodk>=5.9.2",
]
